=== bontiv/vtherm-website/devicesdb/devices.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://www.versatile-thermostat.org/devices.schema.json",
    "title": "Device database",
    "description": "Database of compatible devices with Versatile Thermostat",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "manufacturer": {
                "type": "string",
                "description": "Name of the manufacturer"
            },
            "model": {
                "type": "string",
                "description": "Model number"
            },
            "img": {
                "type": "string",
                "description": "Link to a picture of device. It can be absolute link or relative and image in public/img folder."
            },
            "slug": {
                "type": "string",
                "description": "Sub folder where the device definition is located. It will also be use as slug in URL."
            },
            "state": {
                "enum": [
                    "supported",
                    "community",
                    "unsupported",
                    "partially"
                ],
                "description": "supported: Maintainer supported device | community: report as working by the community | partially: Work with limitations | unsupported: not supported device"
            },
            "title": {
                "type": "string",
                "description": "Title for this device"
            },
            "type": {
                "enum": [
                    "trv",
                    "climate",
                    "electric",
                    "sensor"
                ],
                "description": "Type of device"
            },
            "affiliate": {
                "type": "object",
                "properties": {
                    "fr": {
                        "type": "string"
                    },
                    "de": {
                        "type": "string"
                    },
                    "en": {
                        "type": "string"
                    }
                }
            }
        },
        "required": [
            "manufacturer",
            "model",
            "img",
            "slug",
            "state",
            "type"
        ]
    }
}

=== bontiv/vtherm-website/devicesdb/devices.json
[
    {
        "img": "https://images.squarespace-cdn.com/content/v1/57d112cb9f7456d72f62cd0f/1937c67e-c931-40b9-a66c-ae0fea0a4d43/heatzy-pilote-co%CC%82te%CC%81.jpg",
        "manufacturer": "heatzy",
        "model": "pilote",
        "state": "supported",
        "type": "electric",
        "slug": "heatzy"
    },
    {
        "img": "/img/midea.png",
        "manufacturer": "Midea",
        "model": "",
        "title": "Midea",
        "slug": "midea",
        "state": "supported",
        "type": "climate"
    },
    {
        "img": "https://www.zigbee2mqtt.io/images/devices/SIN-4-1-20.png",
        "manufacturer": "NodOn",
        "model": "SIN-4-1-20",
        "slug": "over-switch",
        "state": "supported",
        "type": "electric",
        "affiliate": {
            "fr": "https://www.domadoo.fr/fr/peripheriques/5688-nodon-micromodule-commutateur-multifonctions-zigbee-16a-3700313925188.html?domid=97",
            "en": "https://www.domadoo.fr/en/peripheriques/5688-nodon-micromodule-commutateur-multifonctions-zigbee-16a-3700313925188.html?domid=97",
            "de": "https://www.domadoo.fr/de/peripheriques/5688-nodon-micromodule-commutateur-multifonctions-zigbee-16a-3700313925188.html?domid=97"
        }
    },
    {
        "img": "https://www.zigbee2mqtt.io/images/devices/SIN-4-FP-21.png",
        "manufacturer": "NodOn",
        "model": "SIN-4-FP-20 / SIN-4-FP-21",
        "slug": "pilot-wire-module",
        "state": "supported",
        "type": "electric",
        "affiliate": {
            "fr": "https://www.domadoo.fr/fr/chauffage-connecte/6828-nodon-module-chauffage-fil-pilote-connecte-zigbee-30.html?domid=97",
            "en": "https://www.domadoo.fr/en/chauffage-connecte/6828-nodon-module-chauffage-fil-pilote-connecte-zigbee-30.html?domid=97",
            "de": "https://www.domadoo.fr/de/chauffage-connecte/6828-nodon-module-chauffage-fil-pilote-connecte-zigbee-30.html?domid=97"
        }
    },
    {
        "img": "https://www.domadoo.fr/18819-large_default/sonoff-high-power-wifi-smart-switch-25a.jpg",
        "manufacturer": "Sonoff",
        "model": "POWR3",
        "slug": "over-switch",
        "state": "supported",
        "type": "electric",
        "affiliate": {
            "fr": "https://www.domadoo.fr/fr/peripheriques/5853-sonoff-commutateur-intelligent-wifi-haute-puissance-25a-6920075776768.html?domid=97",
            "en": "https://www.domadoo.fr/en/peripheriques/5853-sonoff-commutateur-intelligent-wifi-haute-puissance-25a-6920075776768.html?domid=97",
            "de": "https://www.domadoo.fr/de/peripheriques/5853-sonoff-commutateur-intelligent-wifi-haute-puissance-25a-6920075776768.html?domid=97"
        }
    },
    {
        "img": "https://www.zigbee2mqtt.io/images/devices/SNZB-02D.png",
        "manufacturer": "Sonoff",
        "model": "SNZB-02D",
        "slug": "thermometer",
        "state": "supported",
        "type": "sensor",
        "affiliate": {
            "fr": "https://www.domadoo.fr/fr/suivi-energie/6614-sonoff-capteur-de-temperature-et-d-humidite-zigbee-30-avec-ecran-6920075740004.html?domid=97",
            "en": "https://www.domadoo.fr/en/suivi-energie/6614-sonoff-capteur-de-temperature-et-d-humidite-zigbee-30-avec-ecran-6920075740004.html?domid=97",
            "de": "https://www.domadoo.fr/de/suivi-energie/6614-sonoff-capteur-de-temperature-et-d-humidite-zigbee-30-avec-ecran-6920075740004.html?domid=97"
        }
    },
    {
        "img": "https://www.zigbee2mqtt.io/images/devices/SNZB-02P.png",
        "manufacturer": "Sonoff",
        "model": "SNZB-02P",
        "slug": "thermometer",
        "state": "supported",
        "type": "sensor",
        "affiliate": {
            "fr": "https://www.domadoo.fr/fr/chauffage-connecte/6732-sonoff-capteur-de-temperature-et-d-humidite-zigbee-30-avec-support.html?domid=97",
            "en": "https://www.domadoo.fr/en/chauffage-connecte/6732-sonoff-capteur-de-temperature-et-d-humidite-zigbee-30-avec-support.html?domid=97",
            "de": "https://www.domadoo.fr/de/chauffage-connecte/6732-sonoff-capteur-de-temperature-et-d-humidite-zigbee-30-avec-support.html?domid=97"
        }
    },
    {
        "img": "https://www.zigbee2mqtt.io/images/devices/TRVZB.png",
        "manufacturer": "Sonoff",
        "model": "TRVZB",
        "slug": "sonoff-trvzb",
        "state": "supported",
        "type": "trv",
        "affiliate": {
            "fr": "https://www.domadoo.fr/fr/chauffage-connecte/6776-sonoff-tete-thermostatique-zigbee-30-trvzb-compatible-zigbee2mqtt.html?domid=97",
            "de": "https://www.domadoo.fr/de/chauffage-connecte/6776-sonoff-tete-thermostatique-zigbee-30-trvzb-compatible-zigbee2mqtt.html?domid=97",
            "en": "https://www.domadoo.fr/en/chauffage-connecte/6776-sonoff-tete-thermostatique-zigbee-30-trvzb-compatible-zigbee2mqtt.html?domid=97"
        }
    },
    {
        "img": "/img/tuya-ac.jpg",
        "title": "Tuya WIFI",
        "manufacturer": "Tuya",
        "model": "",
        "slug": "tuya-wifi",
        "state": "supported",
        "type": "climate"
    },
    {
        "img": "https://www.zigbee2mqtt.io/images/devices/SSM-U02.png",
        "manufacturer": "Aqara",
        "model": "",
        "title": "Aqara T1",
        "slug": "over-switch",
        "state": "community",
        "type": "electric"
    },
    {
        "img": "https://www.zigbee2mqtt.io/images/devices/WSDCGQ12LM.png",
        "manufacturer": "Aqara",
        "model": "WSDCGQ12LM",
        "slug": "thermometer",
        "state": "community",
        "title": "Aqara T1",
        "type": "sensor",
        "affiliate": {
            "fr": "https://www.domadoo.fr/fr/thermometre-connecte/6705-aqara-capteur-de-temperature-et-d-humidite-zigbee-30-t1-th-s02d-6975833352159.html?domid=97",
            "en": "https://www.domadoo.fr/en/thermometre-connecte/6705-aqara-capteur-de-temperature-et-d-humidite-zigbee-30-t1-th-s02d-6975833352159.html?domid=97",
            "de": "https://www.domadoo.fr/de/thermometre-connecte/6705-aqara-capteur-de-temperature-et-d-humidite-zigbee-30-t1-th-s02d-6975833352159.html?domid=97"
        }
    },
    {
        "img": "https://www.zigbee2mqtt.io/images/devices/LLKZMK12LM.png",
        "manufacturer": "Aqara",
        "model": "LLKZMK12LM / DCM-K01",
        "slug": "over-switch",
        "state": "community",
        "title": "Aqara T2 relay",
        "type": "electric",
        "affiliate": {
            "fr": "https://www.domadoo.fr/fr/module-connecte/6749-aqara-micromodule-double-onoff-zigbee-30-t2-dcm-k01-6970504218635.html?domid=97",
            "en": "https://www.domadoo.fr/en/module-connecte/6749-aqara-micromodule-double-onoff-zigbee-30-t2-dcm-k01-6970504218635.html?domid=97",
            "de": "https://www.domadoo.fr/de/module-connecte/6749-aqara-micromodule-double-onoff-zigbee-30-t2-dcm-k01-6970504218635.html?domid=97"
        }
    },
    {
        "img": "https://www.zigbee2mqtt.io/images/devices/SIN-4-FP-21.png",
        "manufacturer": "Equation",
        "model": "SIN-4-FP-21_EQU",
        "slug": "pilot-wire-module",
        "state": "community",
        "title": "Equation pilot wire module (NodOn)",
        "type": "electric"
    },
    {
        "img": "https://www.zigbee2mqtt.io/images/devices/COZB0001.png",
        "manufacturer": "Eurotronic",
        "model": "COZB0001",
        "slug": "eurotronic-comet",
        "state": "community",
        "type": "trv"
    },
    {
        "img": "https://www.zigbee2mqtt.io/images/devices/CoZB_dha.png",
        "manufacturer": "Eurotronic",
        "model": "CoZB_dha",
        "slug": "eurotronic-comet",
        "state": "community",
        "title": "Eurotronic Comet",
        "type": "trv"
    },
    {
        "img": "https://www.zigbee2mqtt.io/images/devices/064882.png",
        "manufacturer": "Legrand",
        "model": "064879 / 064882",
        "slug": "pilot-wire-module",
        "state": "community",
        "title": "Legrand Celiane with Netatmo cable outlet",
        "type": "electric"
    },
    {
        "img": "https://www.zigbee2mqtt.io/images/devices/BHT-002.png",
        "manufacturer": "Moes",
        "model": "BHT-006",
        "slug": "over-climate",
        "state": "community",
        "type": "climate"
    },
    {
        "manufacturer": "MOES",
        "model": "UFO-R11",
        "img": "https://www.zigbee2mqtt.io/images/devices/UFO-R11.png",
        "state": "community",
        "type": "climate",
        "slug": "smartir",
        "affiliate": {
            "fr": "https://www.domadoo.fr/fr/telecommandes-domotiques/6327-moes-telecommande-universelle-infrarouge-tuya-zigbee-ih-f8260.html?domid=97",
            "en": "https://www.domadoo.fr/en/telecommandes-domotiques/6327-moes-telecommande-universelle-infrarouge-tuya-zigbee-ih-f8260.html?domid=97",
            "de": "https://www.domadoo.fr/de/telecommandes-domotiques/6327-moes-telecommande-universelle-infrarouge-tuya-zigbee-ih-f8260.html?domid=97"
        }
    },
    {
        "img": "https://www.domadoo.fr/25997-large_default/moes-temperature-and-humidity-sensor-with-zigbee-display-tuya.jpg",
        "manufacturer": "Moes",
        "model": "ZSS-KB-TH-LF-C",
        "slug": "thermometer",
        "state": "community",
        "type": "sensor",
        "affiliate": {
            "fr": "https://www.domadoo.fr/fr/domotique/6667-moes-capteur-de-temperature-et-humidite-avec-ecran-zigbee-tuya.html?domid=97",
            "en": "https://www.domadoo.fr/en/domotique/6667-moes-capteur-de-temperature-et-humidite-avec-ecran-zigbee-tuya.html?domid=97",
            "de": "https://www.domadoo.fr/de/domotique/6667-moes-capteur-de-temperature-et-humidite-avec-ecran-zigbee-tuya.html?domid=97"
        }
    },
    {
        "img": "https://www.zigbee2mqtt.io/images/devices/NAS-TH07B2.png",
        "manufacturer": "Neo",
        "model": "NAS-TH07B3",
        "slug": "thermometer",
        "state": "community",
        "type": "sensor",
